# Generated by Django 4.1.3 on 2022-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='blog/banners')),
                ('descripcion', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
